### ISSUE TITLE
How to set granularmode option to true

### ISSUE THREAD

**Issue by shreyagoyal06** [davidbrowaeys/DXB#55]
How to set granularmode option to true in azure devops yml in which we are using the DXB Plugin
Issue is I'm deploying only a field and whole object is getting deployed

**Comment by davidbrowaeys** [comment]
Hello @shreyagoyal06 thank you for reaching out.  What version are you using ? 

Normally with -g it should do the job : 
`
sf dxb source delta -m branch -k origin/master -g -p delta
`

**Example** 
![image](https://github.com/user-attachments/assets/ae3c6b77-e988-437e-9a45-9123c97e4ae5)

PS: please note that back in the days there was a bug in the salesforce cli when you try to deploy a single custom field/validation rule that belong to a custom object that is link with a master details where the OWD is set as "controlled by parent". I can't remember exactly the error(something like you try to convert the master detail to a lookup or something). But that's why I deploy the whole object but understand that sometimes an object can be really big. The workaround was to make also a dummy change on the master-detail field. I am not sure if that bug has been fixed since then.

**Comment by shreyagoyal06** [comment]
Hi @davidbrowaeys thank you so much for the prompt response. The -g attribute worked.
I will surely keep an eye out for the SF error you mentioned.

Also, I had one query
The destructiveChanges.xml is automatically created with this plugin or we have to manually provide it?

**Comment by davidbrowaeys** [comment]
The original idea was to generate a destructiveChanges.xml manifest base on the file you delete in the repo. But technically this is more complicated. So  destructive change is not something I am supporting anymore. Certain metadata like workflow or custom labels shared a common file. When you want to delete a single workflow you don't delete the file itself.

I will close this issue as I think we have answer the main request :) Feel free to reach out if you have more questions. 
I am glad you are using it :)
